feat(#1) add and extends juststeveking laravel data object tools

diff --git a/gitlab-ci/deploy.yml b/gitlab-ci/deploy.yml
--- a/gitlab-ci/deploy.yml
+++ b/gitlab-ci/deploy.yml
@@ -12,15 +12,17 @@ publish:
     - body=$(echo "$response" | head -n 1)
     # Output state information
     - if [ $code -eq 201 ]; then
-        echo "Package created - Code $code - $body";
+      echo "Package created - Code $code - $body";
       else
-        echo "Could not create package - Code $code - $body";
-        exit 1;
+      echo "Could not create package - Code $code - $body";
+      exit 1;
       fi
   environment:
     name: production
     url: https://gitlab.example.com/api/v4/group/$CI_GROUPID/-/packages/composer/
   rules:
-    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
+    - if: $CI_PIPELINE_SOURCE == "push"
+      when: never
+    - if: $CI_COMMIT_TAG =~ /^\d+.\d+.\d+-?.*$/
+    - if: $CI_COMMIT_BRANCH
       when: manual
-
